### ISSUE TITLE
Grid类bug

### ISSUE THREAD

**Issue by Hahawillll** [hawind/gdoo#11]
Grid类下的recursiveJoin方法有一句static::recursiveJoin($joins, $k)，具体意义不明，会导致部分页面死循环，注释掉就正常了

**Comment by Hahawillll** [comment]
仔细研究了一下，应该是341行的判断出的问题。把==改成===或者全转换成字符串应该就正常了

**Comment by hawind** [comment]
c0e035a 已经修复
