### ISSUE TITLE
Demo 网站，鼠标移动到第三级菜单，菜单就直接关闭了，点都点不到。

### ISSUE THREAD

**Issue by gotounix** [hawind/gdoo#8]

**Comment by gotounix** [comment]
Microsoft Edge
版本 95.0.1020.44 (官方内部版本) (64 位)

**Comment by hawind** [comment]
可以截图看一下吗，需要复现一下。

**Comment by gotounix** [comment]
@hawind 刚刚测试了下，又可以了，很奇怪，就是鼠标移到第三级菜单的时候，这个菜单就会消失，无法点击第三级菜单。
